
ps:
	iverilog -g2012 -o pixelSensor -c pixelSensor.fl
	vvp -n pixelSensor
	
pa:
	iverilog -g2012 -o pixelArray -c pixelArray.fl
	vvp -n pixelArray
	
SM: 
	iverilog -g2012 -o stateMachine -c stateMachine.fl
	vvp -n stateMachine
